  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/jquery.3.2.1.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/popper.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/bootstrap.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/chartist.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/chartist-plugin-tooltip.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/bootstrap-notify.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/bootstrap-toggle.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/jquery.mapael.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/world_countries.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/circles.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/jquery.scrollbar.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/ready.min.js"></script>--%>
  <%--<script type="text/javascript" src="<%=basePath%>assets/js2/demo11111111111.js"></script>--%>

  <script type="text/javascript" src="<%=basePath%>assets/js/core/jquery.3.2.1.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/core/popper.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/core/bootstrap.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/chartist/chartist.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/jquery-mapael/jquery.mapael.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/jquery-mapael/maps/world_countries.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/chart-circle/circles.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/ready.min.js"></script>
  <script type="text/javascript" src="<%=basePath%>assets/js/demo11111111111.js"></script>

