package info.lzzy.dao;

import info.lzzy.models.Api;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface ApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    @Delete({
        "delete from api",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    @Insert({
        "insert into api (id, role, ",
        "name, info, url, ",
        "type, state, succeed_html, ",
        "defeated_html, add_time, ",
        "request_data)",
        "values (#{id,jdbcType=VARCHAR}, #{role,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{info,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{state,jdbcType=INTEGER}, #{succeedHtml,jdbcType=VARCHAR}, ",
        "#{defeatedHtml,jdbcType=VARCHAR}, #{addTime,jdbcType=TIMESTAMP}, ",
        "#{requestData,jdbcType=VARCHAR})"
    })
    int insert(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    int insertSelective(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, role, name, info, url, type, state, succeed_html, defeated_html, add_time, ",
        "request_data",
        "from api",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("info.lzzy.dao.ApiMapper.BaseResultMap")
    Api selectByPrimaryKey(String id);


    @Select({
            "select",
            "id, role, name, info, url, type, state, succeed_html, defeated_html, add_time, ",
            "request_data",
            "from api",
            "where role = #{role,jdbcType=VARCHAR}"
    })
    @ResultMap("info.lzzy.dao.ApiMapper.BaseResultMap")
    List<Api> selectByRole(String role);

    @Select({"select * from api WHERE (role = #{role}) and\n" +
            "    (name like concat('%',#{kw},'%') or info like concat('%',#{kw},'%'))"
    })
    @ResultMap("info.lzzy.dao.ApiMapper.BaseResultMap")
    List<Api> selectByRoleAndKw(@Param("role") String role,@Param("kw") String kw);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    @Update({
        "update api",
        "set role = #{role,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "info = #{info,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=INTEGER},",
          "succeed_html = #{succeedHtml,jdbcType=VARCHAR},",
          "defeated_html = #{defeatedHtml,jdbcType=VARCHAR},",
          "add_time = #{addTime,jdbcType=TIMESTAMP},",
          "request_data = #{requestData,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Api record);
}